### ISSUE TITLE
xxd not available when using neovim

### ISSUE THREAD

**Issue by MeisterP** [zimfw/pvenv#1]
I'm using neovim and therefore don't have `xxd` installed on my system. 

```
pvenv ls
pvenv:18: command not found: xxd
```

So either mention that this module depends on `vim` or implement the function without relying on an external binary (no zsh wizard... so I don't know whether that's even possible).

**Comment by ericbn** [comment]
HI @MeisterP. I've fixed this using python3 instead of xxd and other tools.

**Comment by ericbn** [comment]
@MeisterP, just out of curiosity: are you installing this module using Zim or some other Zsh framework? I'm almost regretting I've added the instructions for ohmyzsh there, and I'm considering removing that.

**Comment by MeisterP** [comment]
> installing this module using Zim or some other Zsh framework?

I'm using Zim
